ALTER TABLE empleado
    ALTER COLUMN email TYPE VARCHAR(60);
ALTER TABLE empleado
    ALTER COLUMN email SET NOT NULL;

ALTER TABLE empleado
    ADD CONSTRAINT empleado_email_unique UNIQUE (email);

CREATE TABLE empleado
(
    id         SERIAL PRIMARY KEY,
    nombre     VARCHAR(150)       NOT NULL,
    apellido   varchar(150)       not null,
    ruc        VARCHAR(20) UNIQUE NOT NULL,
    direccion  TEXT,
    telefono   VARCHAR(20),
    email      VARCHAR(60),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/*Insertar Datos*/
INSERT INTO empleado (nombre, apellido, ruc, direccion, telefono, email)
VALUES
        ('Carlos', 'Ramírez', '12345678901', 'Av. Siempre Viva 742, Lima', '987654321', 'carlos.ramirez@email.com'),
        ('María', 'Gómez', '10987654321', 'Calle Los Olivos 123, Arequipa', '912345678', 'maria.gomez@email.com'),
        ('Luis', 'Fernández', '11223344556', 'Jr. Las Flores 456, Cusco', '998877665', 'luis.fernandez@email.com'),
        ('Ana', 'Torres', '22334455667', 'Av. La Marina 890, Trujillo', '955443322', 'ana.torres@email.com'),
        ('Jorge', 'Castillo', '33445566778', 'Calle Principal 321, Piura', '944332211', 'jorge.castillo@email.com')

select*
from empleado;

/* Creaciones de roles*/
CREATE TABLE role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO role (name, description)
VALUES ('ADMIN', 'Administrador del sistema'),
       ('RRHH', 'Recursos Humanos'),
       ('EMPLOYEE', 'Empleado estándar');

select *
from role;

/*Usuairo*/
CREATE TABLE app_user
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(100) NOT NULL UNIQUE,
    email           VARCHAR(150) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    account_locked  BOOLEAN      NOT NULL DEFAULT FALSE,
    failed_attempts INT                   DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    role_id         BIGINT       NOT NULL,
    CONSTRAINT fk_user_role
        FOREIGN KEY (role_id)
            REFERENCES role (id)
            ON DELETE RESTRICT
);

INSERT INTO app_user (username, email, password_hash, role_id)
VALUES ('admin1', 'admin1@empresa.com', '$2a$10$hashsimulado1', 1),
       ('rrhh1', 'rrhh1@empresa.com', '$2a$10$hashsimulado2', 2),
       ('empleado1', 'empleado1@empresa.com', '$2a$10$hashsimulado3', 3);

select *
from app_user;

/*Creacion de empleado*/
CREATE TABLE empleado
(
    id         SERIAL PRIMARY KEY,
    nombre     VARCHAR(150)       NOT NULL,
    apellido   varchar(150)       not null,
    ruc        VARCHAR(20) UNIQUE NOT NULL,
    direccion  TEXT,
    telefono   VARCHAR(20),
    email      VARCHAR(60),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

/*Creaacion de departamentos*/
CREATE TABLE department
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
select *
from department

select*
from app_user